apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: simpleflaskapp
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 3000
        env:
        - name: OTEL_ENDPOINT
          value: otel-collector:4317